@host = http://localhost:9999

GET {{host}}/posts/

###

GET {{host}}/posts/fresh-check/8

###

DELETE {{host}}/posts/2

###

POST {{host}}/posts/like/9

###

POST {{host}}/posts/
Content-Type: application/json

{
    "content": "New Post"
}
